### ISSUE TITLE
Expertify Rocket Fuel Recipe

### ISSUE THREAD

**Issue by DragonmasterDJ** [NillerMedDild/Enigmatica2ExpertSkyblock#255]
After taking a look at rocket fuel, I noticed that the recipe is still quite easy to make, maybe it could be made harder.

What could happen is that the player is required to make a distillation tower for the rocket fuel to be made? And by doing so they would have to make Diesel, Napalm, Oxygen and Hydrogen in a mixer. or in a modular machine, etc.

This would just give the jump into space travel slightly more difficulty!

**Comment by Rodg88** [comment]
Probably a bit late as this change has been implemented already, but just wondering if there wasn't a way to use the actual gasoline in the recipe instead of the bitumen item? And the recipe using bitumen and tar is a little weird from a space nerd's point of view lol

If you went for mixing two liquids together, maybe a NC chemical reactor would work?

There is also 'rocket fuel' from EIO (the vat doesn't require titanium), or TE's refined fuel for other options for the fuel component

**Comment by NillerMedDild** [comment]
I'm not really going for realism here. TE Refined Fuel can already be used to fuel rockets.
